name: node

on:
  push:
      branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
        
    - name: Build and upload to aliyun
      run: |
        docker login --username=${{ secrets.ALI_REPO_USER }} --password=${{ secrets.ALI_REPO_PASSWORD }} registry.ap-northeast-1.aliyuncs.com
        docker build -t registry.ap-northeast-1.aliyuncs.com/oak-cloud/mai2-update-index:latest .
        docker push registry.ap-northeast-1.aliyuncs.com/oak-cloud/mai2-update-index:latest

